### PR TITLE
Add embeds for answers

### PR DESCRIPTION
**Pull request by gubareve**
image

### CODE REVIEW

**Comment by gubareve** [comment]
Although I have tested this on the beta bot, It might be unstable. Please test it, review it, and then merge it. I can handle updating heroku.

**Comment by WickedTree** [comment]
Hmm… Ok. Will test

**Comment by WickedTree** [comment]
Make it so that it replaces the embed with Correct after 10 seconds of showing the embed

**Comment by gubareve** [comment]
Idk, the problem with that is that people just see a bunch of corrects and thats just un-intuitive.

**Pull request merged**
